CREATE TABLE IF NOT EXISTS "URLManager" (
  "ID" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  "HASH" char(128) NOT NULL,
  "URL" char(128) NOT NULL,
  "DATE" char(128) NOT NULL
);
CREATE TABLE IF NOT EXISTS "Users" (
  "ID" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  "NAME" char(128) NOT NULL,
  "EMAIL" char(128) NOT NULL,
  "USERNAME" char(128) NOT NULL,
  "PASSWORD" char(128) NOT NULL,
  "USERTYPE" int(2) NOT NULL
);
